FORMAT: 1A
HOST: https://martini-25luglio-flight.herokuapp.com/

# flightexamAPI

flightAPI is an api to get infos about flights

## All Flights [/flights/]

You might request an airport code and the selector (departure or arrival) that you want to get the flight code of each plane landing or taking off from that specific airport
### List All Flights from an Airport [GET]


+ Response 200 (application/json)

        [
            "UL871","SQ388"
        ]

## Flight Info [/flightInfo/]
You might request the information about a specific flight, if you know the flight code
### List the information about a specific flight [GET]

+ Response 200 (application/json)

        {
            "departureAirport":"MXP",
            "arrivalAirport":"JFK",
            "delay":37
        }